### ISSUE TITLE
`rimraf`'s `bin.js` file non existent

### ISSUE THREAD

**Issue by bee344** [paritytech/substrate-js-dev#119]
In version `v5.0.5` of `rimraf`, the file structure changes and `bin.js` is no longer present in the `node_modules`, which causes [this](https://github.com/paritytech/substrate-js-dev/blob/main/scripts/importBinary.cjs) to fail and therefore crashes the build of `txwrapper`. We need to further check how deep this difference goes and refactor the call.

Rel: [#358](https://github.com/paritytech/txwrapper-core/issues/358)

**Comment by TarikGul** [comment]
I have a decent solution for the following, I'll get something going and ping you.

**Comment by TarikGul** [comment]
This is now fixed and resolved in #129, next release will reflect it.
