### ISSUE TITLE
Add `version` flag to update-pjs scripts

### ISSUE THREAD

**Issue by TarikGul** [paritytech/substrate-js-dev#65]
When calling `substrate-update-pjs-deps` there is no way to currently specify a version you would like to set the packages and resolutions too. It would be nice to be able to pass in a flag, and it will update all the version to the set value. To implement this would be pretty straight forward, as no fetching is required. In `main()` we would just have a quick check that says something like `argv.version || fetchRelease()['tag_name']`

**Comment by mlshv** [comment]
Hello there! I'd like to contribute on this issue. But I don't get how it is supposed to work. As I can see, not all the `@polkadot` packages have the same version number. 

<img width="295" alt="Снимок экрана 2022-05-06 в 13 37 41" src="https://user-images.githubusercontent.com/16861579/167073392-7efb24a4-317c-4bc3-88b0-aeafc2ea6922.png">

For example, how do I set version of `@polkadot/apps-config`?

@TarikGul

**Comment by TarikGul** [comment]
Great point, that is totally correct and a good catch. We'll have to specify a package group as well. Maybe we set the flag for the package too `--packageVersion` -> which the value passed in could be expected to be like: `apps-config@3.1.1`, that way we know the package, and the corresponding version.

**Comment by TarikGul** [comment]
Would take some simple parsing/splitting but that's the first thing that came to mind

**Comment by TarikGul** [comment]
Closing as this is not needed anymore.
